### ISSUE TITLE
MLS for end to end encryption

### ISSUE THREAD

**Issue by erkinalp** [spacebarchat/client#116]
- [ ] Message format handling
- [ ] Obey encryption permissions
- [ ] Manage encryption permissions
- [ ] Establish group keys
- [ ] Send and receive encrypted messages
- [ ] Force key rotation UX
