### ISSUE TITLE
Event and moderation duty scheduler

### ISSUE THREAD

**Issue by erkinalp** [spacebarchat/client#58]
Based on https://github.com/x127f/timetable-generator

Bigger guilds may wish to roster the moderators, or tightly pack the events to maximise the human resource utilisation. This feature would be useful to help them utilise the human resource. In case of rostered moderators, an enforcement mechanism can be considered even, in the form of force-switching to the guild that scheduled the moderation duty and preventing de-focussing out of the guild in question.

- [ ] Add/remove constraints
- [ ] Import/export rosters
- [ ] Event scheduling in a guild
- [ ] Moderation duty scheduling in a guild
  - [ ] Force-switch to the relevant channel and prevent leaving it
  - [ ] Disable self-deafing for the moderators with ongoing moderation duty in that voice channel
