### ISSUE TITLE
Entertainment and training features

### ISSUE THREAD

**Issue by erkinalp** [spacebarchat/client#76]
Making discord.com's 2022 April fools into a serious fosscord feature:

- [ ] Confetti
- [ ] Cheers
- [ ] Achievements
  - [ ] Client-global achievements
  - [ ] Server-global achievements
  - [ ] Per-guild achievements
  - [ ] Per-group achievements
- [ ] Screen shake events 
- [ ] `@someone`

Related: fosscord/fosscord-server#687
