### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TheArcaneBrony** [spacebarchat/client#94]
## Core Web app
- [ ] User Management: Kick, Ban, Timeout
- [ ] Message Management: Edit, Delete
- [ ] Create/Delete/Move Channels
- [ ] Member List
- [ ] User Mentions/Notifications
- [ ] DMs/Friending
- [ ] Basic Guild Settings
- [x] Embeds
- [ ] User Profile Modals
- [ ] Settings
- [ ] Guild Info Modals
- [ ] Improved Forms
- [x] Attachment Uploading
- [x] Channel Permissions
- [ ] Typing Event
- [ ] Message Reactions
- [ ] Unknown Channel/Guild Screen

## Tauri
- [ ] Hardware Security Keys for 2FA (https://github.com/tauri-apps/tauri-plugin-authenticator)
- [ ] Logging (https://github.com/tauri-apps/tauri-plugin-log)
- [ ] Data storage (https://github.com/tauri-apps/tauri-plugin-store)
- [ ] Sentry (https://github.com/timfish/sentry-tauri)
- [ ] Enhanced Clipboard (https://github.com/CrossCopy/tauri-plugin-clipboard)
- [ ] Auto Updating (https://tauri.app/v1/guides/distribution/updater)
- [ ] Update Server (https://github.com/KilleenCode/tauri-update-cloudflare)
